AWSTemplateFormatVersion: "2010-09-09"
Description: demo global load balancer

Resources:
  Accelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: !Sub '${AWS::StackName}'
      Enabled: true
      IpAddressType: IPV4

  Listener:
    Type: AWS::GlobalAccelerator::Listener
    Properties:
      AcceleratorArn: !Ref Accelerator
      Protocol: TCP
      PortRanges:
        - FromPort: 80
          ToPort: 80
      ClientAffinity: NONE

Outputs:
  DnsName:
    Value: !GetAtt Accelerator.DnsName
  GlobalAcceleratorListener:
    Value: !Ref Listener
